### ISSUE TITLE
이미지 서버 구축

### ISSUE THREAD

**Issue by TaemHam** [YOUNGHO0/Filmdoms_Project#10]
아마존 S3의 프리티어 요금으로 이미지 서버를 구축한다.

**Comment by YOUNGHO0** [comment]
아마존 S3 프리티어 요금으로 이미지 서버 구축을 완료하였습니다.
엑세스 키, 시크릿 키는 따로 전달할 예정입니다!

**Comment by YOUNGHO0** [comment]
아마존 S3 프리티어 요금으로 이미지 서버 구축을 완료하였습니다.
엑세스 키, 시크릿 키는 따로 전달할 예정입니다!
